// var adjective = (lead, suffix) => {
//   if (suffix) {
//     return { lead, suffix};
//   }
//   return { lead, suffix: lead };
// };

// var adjectiveItem = adjective('Bloody', 'Blood');
// var adjectiveautumn = adjective('Autumn');

// var lib = {
//   adjectives: [
//     adjective('Bloody', 'Blood'),
//     adjective('Autumn')
//   ]
// }

// var nameFwd = `${adjectiveItem.lead} Mary`;
// var nameOf = `Mary of ${adjectiveItem.suffix}`;

var library = {
  "adjectives": [
    "Bloody",
    "Bright",
    "Crazy",
    "Damned",
    "Defiant",
    "Drifting",
    "Fleeting",
    "Flying",
    "Forward",
    "Fortunate",
    "Heavenly",
    "Infinite",
    "Intrepid",
    "Iron",
    "Laughing",
    "Lone",
    "Lucid",
    "Mount",
    "Platinum",
    "Quantum",
    "Raving",
    "Relentless",
    "Sandy",
    "Silent",
    "Silk",
    "Sleeping",
    "Sonic",
    "Steel",
    "Thieving",
    "Thundering",
    "Wailing",
    "Wandering",
    "Wayward",
    "Weeping",

    // colours
    "Aqua",
    "Azure",
    "Black",
    "Blue",
    "Crimson",
    "Cyan",
    "Gray",
    "Green",
    "Grey",
    "Indigo",
    "Lavender",
    "Magenta",
    "Maroon",
    "Onyx",
    "Orange",
    "Purple",
    "Red",
    "Rouge",
    "Silver",
    "Turquoise",
    "Violet",
    "White",
    "Yellow",

    // Numbering
    "First",
    "Second",
    "Third",
    "Fourth",
    "Fifth",
    "Sixth",
    "Seventh",
    "Eighth",
    "Ninth",
    "Tenth"
  ],
  "nouns": [
    // Months
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",

    "Ambassador",
    "Angel",
    "Ark",
    "Aurora",
    "Autumn",
    "Bane",
    "Balance",
    "Banshee",
    "Bird",
    "Bull",
    "Butterfly",
    "Cartographer",
    "Challenger",
    "Chariot",
    "Child",
    "Columbia",
    "Column",
    "Comet",
    "Constellation",
    "Constitution",
    "Continuum",
    "Crusader",
    "Crystal",
    "Daedalus",
    "Dawn",
    "Desert",
    "Discovery",
    "Dreamer",
    "Enterprise",
    "Endeavour",
    "Eternity",
    "Equinox",
    "Fire",
    "Firefly",
    "Fortune",
    "Fog",
    "Galaxy",
    "Genesis",
    "Griffin",
    "Gulf",
    "Hail",
    "Hammer",
    "Horror",
    "Horse",
    "Hunter",
    "Hurricane",
    "Iceberg",
    "Infinity",
    "Inquisitor",
    "Insomniac",
    "Javelin",
    "Jenny",
    "Judgement",
    "Knight",
    "Lancaster",
    "Lance",
    "Leviathan",
    "Lord",
    "Magpie",
    "Marble",
    "Mary",
    "Midnight",
    "Mist",
    "Moth",
    "Mountain",
    "Nebula",
    "Night",
    "Orion",
    "Paladin",
    "Pearl",
    "Pillar",
    "Prometheus",
    "Rain",
    "Raven",
    "Regent",
    "Revenge",
    "Ribbon",
    "Risk",
    "River",
    "Robin",
    "Rocinante",
    "Rogue",
    "Royal",
    "Sand",
    "Sea",
    "Serenity",
    "Shadowfax",
    "Shark",
    "Snow",
    "Solstice",
    "Somnambulist",
    "Son",
    "Sovereign",
    "Spider",
    "Spring",
    "Spartan",
    "Specter",
    "Spectre",
    "Spirit",
    "Stone",
    "Storm",
    "Summer",
    "Sun",
    "Sunrise",
    "Surprise",
    "Terrier",
    "Terror",
    "Thunder",
    "Titan",
    "Tornado",
    "Tsunami",
    "Tundra",
    "Universe",
    "Vampire",
    "Vengeance",
    "Wanderer",
    "War",
    "Warbird",
    "Weasel",
    "Widow",
    "Winter",
    "Wrath",
    "Yorktown",

    // Radio
    "Alpha",
    "Bravo",
    "Charlie",
    "Delta",
    "Echo",
    "Foxtrot",
    "Golf",
    "Hotel",
    "India",
    "Juliett",
    "Kilo",
    "Lima",
    "Mike",
    // "November",
    "Oscar",
    "Papa",
    "Quebec",
    "Romeo",
    "Sierra",
    "Tango",
    "Uniform",
    "Victor",
    "Whiskey",
    "X-ray",
    "Yankee",
    "Zulu"
  ]
}
